name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12pm UTC
    - cron: '0 12 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-20.04
    steps:
      - uses: avinal/Profile-Readme-WakaTime@v3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "master"
          COMMIT_MSG: "new stats received :dog:"
